# Generated by Django 5.0.3 on 2024-03-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_remove_consumeditems_user_delete_date_input_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='carrer_obj',
            field=models.TextField(null=True),
        ),
    ]
